apiVersion: v1
data:
  index.html: "hello"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginxconf

---

apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nginxconf
        mountPath: /usr/share/nginx/html/
  volumes:
    - name: nginxconf
      configMap:
        name: nginxconf
