apiVersion: v1
data:
  index.html: aGVsbG8gCg==
kind: Secret
metadata:
  name: nginx-secret
---

apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: nginx-secret
          readOnly: true
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: nginx-secret
      secret:
        secretName: nginx-secret